### ISSUE TITLE
CommunicationsException

### ISSUE THREAD

**Issue by andeliero92** [scalikejdbc/hello-scalikejdbc#10]
Hi, i've implemented my entities like this example. But after one day of running application i got this error:

```
2016-08-12 08:52:55,993 [ERROR] from application in application-akka.actor.default-dispatcher-34 - POST /token
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 49,378,946 milliseconds ago.  The last packet sent successfully to the server was 49,378,946 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3739)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2508)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
    at com.mysql.jdbc.ConnectionImpl.setReadOnlyInternal(ConnectionImpl.java:4984)
    at com.mysql.jdbc.ConnectionImpl.setReadOnly(ConnectionImpl.java:4977)
    at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:562)
    at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:562)
    at scalikejdbc.DBConnection$class.scalikejdbc$DBConnection$$setReadOnly(DBConnection.scala:89)
    at scalikejdbc.DBConnection$class.readOnlySession(DBConnection.scala:179)
    at scalikejdbc.NamedDB.readOnlySession(NamedDB.scala:17)
    at scalikejdbc.DBConnection$$anonfun$readOnly$1.apply(DBConnection.scala:190)
    at scalikejdbc.DBConnection$$anonfun$readOnly$1.apply(DBConnection.scala:190)
    at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
    at scalikejdbc.NamedDB.using(NamedDB.scala:17)
    at scalikejdbc.DBConnection$class.readOnly(DBConnection.scala:190)
    at scalikejdbc.NamedDB.readOnly(NamedDB.scala:17)
    at scalikejdbc.SQLToResult$class.apply(SQL.scala:676)
    at scalikejdbc.SQLToOptionImpl.apply(SQL.scala:846)
    at models.commons.storage.UserSql$$anonfun$findByNameAndPassword$1.apply(UserSql.scala:41)
    at models.commons.storage.UserSql$$anonfun$findByNameAndPassword$1.apply(UserSql.scala:37)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3721)
    ... 28 common frames omitted`
```

Are you sure the connectionPool is properly used?

**Comment by seratch** [comment]
This project just shows you how scalikejdbc in Play apps work with H2 database. Ensure your mysql connection settings. https://github.com/scalikejdbc/hello-scalikejdbc/blob/master/conf/application.conf

scalikejdbc uses commons-dbcp2 by default. If you prefer using other connection pool implementation such as HikariCP, properly configure by yourself like this: http://scalikejdbc.org/documentation/connection-pool.html
